#!/bin/zsh

# Based on https://github.com/justmendes/dotfiles/blob/master/install .

GREEN='\033[1;32m'
BLUE='\033[1;34m'
RED='\033[1;91m'
RESET='\033[0m'
DOTFILES=~/.dotfiles

function pp {
  echo -e "\n$1[$2]: $3${RESET}"
}

function pp_info {
  pp $BLUE $1 $2
}

function pp_success {
  pp $GREEN $1 $2
}

function pp_error {
  pp $RED $1 $2
}

function dirlink {
  (cd $HOME && ln -s "$WD/$1" "$2")
}

pp_info "install" "Setting up developer directory"
mkdir -p ~/Developer

pp_info "install" "Setting up dotfiles directory"
git clone https://github.com/joaofcosta/dotfiles.git $DOTFILES

pp_info "install" "Installing Homebrew"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

pp_info "macos" "Installing command line tools"
xcode-select --install

# ------------------------------
# ZSH
# ------------------------------

pp_info "zsh" "Replacing system zsh with brew version"
sudo sh -c "echo $(which zsh) >> /etc/shells"
chsh -S $(which zsh)

pp_info "zsh" "Setting up environment"
ln -s $HOME/.dotfiles/zsh/.zshrc $HOME/.zshrc

# ------------------------------
# NeoVim
# ------------------------------

pp_info "nvim" "Installing NeoVim"
brew install neovim

pp_info "nvim" "Installing system python 2.7 for compatibility purposes"
brew install python@2

pp_info "nvim" "Installing language libs"
/usr/local/bin/pip2 install neovim
pip install neovim
gem install neovim
yarn global add neovim

pp_info "nvim" "Installing vim-plug"
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

pp_info "nvim" "Installing remaining plugins"
nvim -u $HOME/.dotfiles/nvim/plugins.vim +PlugInstall +qall

pp_info "nvim" "Updating remote plugins"
nvim +UpdateRemotePlugins +qall

# ------------------------------
# Alacritty
# ------------------------------

pp_info "alacritty" "Installing Alacritty"
brew cask install alacritty

pp_info "alacritty" "Setting up environment"
ln -s ~/.dotfiles/alacritty/alacritty.yml ~/.config/alacritty/alacritty.yml
